In [ ]:
import pandas as pd
import numpy as np

In [ ]:
from google.colab import files

uploaded = files.upload()

dataraw_file = list(uploaded.keys())[0]


Saving Dataa.csv to Dataa.csv


In [ ]:
response_data = pd.read_csv('Dataa.csv')
response_data

Timestamp  ... Label
0     7/4/2020 212646  ...     0
1     7/8/2020 112705  ...     0
2     7/8/2020 114242  ...     0
3     7/8/2020 152511  ...     0
4     7/8/2020 154337  ...     0
..                ...  ...   ...
122  7/23/2020 184340  ...     0
123  7/23/2020 185434  ...     0
124  7/23/2020 185907  ...     0
125  7/23/2020 192041  ...     0
126  7/24/2020 160328  ...     0

[127 rows x 24 columns]

In [ ]:
response_data.dtypes

Timestamp                                                                                          object
Email Address                                                                                      object
Jenis Kelamin Anak                                                                                  int64
Berat Badan Lahir Anak (isi dalam kg)                                                             float64
Tinggi Badan Lahir Anak (isi dalam cm)                                                            float64
Berat Badan Anak sekarang (isi dalam kg)                                                          float64
Tinggi Badan Anak sekarang (isi dalam cm)                                                         float64
Pendidikan Terakhir Ayah                                                                            int64
Pendidikan Terakhir Ibu                                                                             int64
Tinggi Ibu (perkiraan dalam cm)               

In [ ]:
response_data = response_data.astype({'Label' : 'category'})
response_data = response_data.astype({'Jenis Kelamin Anak' : 'category'})
response_data = response_data.astype({'Pendidikan Terakhir Ayah' : 'category'})
response_data = response_data.astype({'Pendidikan Terakhir Ibu': 'category'})
response_data = response_data.astype({'Berapa kali pemeriksaan kehamilan' : 'category'})
response_data = response_data.astype({'Tempat persalinan' : 'category'})
response_data = response_data.astype({'Anak pernah mengalami ISPA (Infeksi Saluran Pernapasan Akut) seperti batuk. pilek. sinus. dsb?' : 'category'})
response_data = response_data.astype({'Anak pernah mengalami diare?' : 'category'})
response_data = response_data.astype({'Apakah anak batuk dalam 3 bulan terakhir?' : 'category'})
response_data.dtypes

Timestamp                                                                                           object
Email Address                                                                                       object
Jenis Kelamin Anak                                                                                category
Berat Badan Lahir Anak (isi dalam kg)                                                              float64
Tinggi Badan Lahir Anak (isi dalam cm)                                                             float64
Berat Badan Anak sekarang (isi dalam kg)                                                           float64
Tinggi Badan Anak sekarang (isi dalam cm)                                                          float64
Pendidikan Terakhir Ayah                                                                          category
Pendidikan Terakhir Ibu                                                                           category
Tinggi Ibu (perkiraan dalam cm)      

In [ ]:
response_data_clear = response_data.drop(["Timestamp", "Email Address"], axis=1)
print(response_data_clear)

    Jenis Kelamin Anak  ...  Label
0                    0  ...      0
1                    1  ...      0
2                    1  ...      0
3                    1  ...      0
4                    0  ...      0
..                 ...  ...    ...
122                  1  ...      0
123                  1  ...      0
124                  0  ...      0
125                  0  ...      0
126                  1  ...      0

[127 rows x 22 columns]


In [ ]:
#Feature Selection menggunakan chi-square
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2

x = response_data_clear.iloc[:,0:22]
y = response_data_clear.iloc[:,-1]

bestfeatures = SelectKBest(score_func=chi2, k=10)
fit= bestfeatures.fit(x,y)

dfscores = pd.DataFrame(fit.scores_)
dfcolumns = pd.DataFrame(x.columns)

featureScores = pd.concat([dfcolumns,dfscores],axis=1)
featureScores.columns = ['Specs','Score']

featureScores

print(featureScores.nlargest(10, 'Score'))

In [ ]:
from sklearn.feature_selection import RFE
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import Normalizer
from sklearn import preprocessing

x = response_data_clear.iloc[:,0:22]
y = response_data_clear.iloc[:,-1]

model = LogisticRegression(solver='lbfgs')
rfe = RFE(model, 3)
fit = rfe.fit(x, y)

dfscores = pd.DataFrame(fit.ranking_)
dfcolumns = pd.DataFrame(x.columns)

featureScores = pd.concat([dfcolumns,dfscores],axis=1)
featureScores.columns = ['Specs','Score']

featureScores
#print(featureScores.nlargest(10, 'Score'))

/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)
/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression


Specs  Score
0                                  Jenis Kelamin Anak      3
1               Berat Badan Lahir Anak (isi dalam kg)      9
2              Tinggi Badan Lahir Anak (isi dalam cm)     10
3            Berat Badan Anak sekarang (isi dalam kg)     16
4           Tinggi Badan Anak sekarang (isi dalam cm)     11
5                            Pendidikan Terakhir Ayah      4
6                             Pendidikan Terakhir Ibu      8
7                     Tinggi Ibu (perkiraan dalam cm)     14
8                    Tinggi Ayah (perkiraan dalam cm)     18
9                             Jumlah anggota keluarga      5
10             Perkiraan pendapatan dalam satu bulan      19
11                                         PENGASUHAN     12
12                                               GIZI     17
13                                         KEBERSIHAN     15
14                                  KEBERSIHAN BALITA      2
15                  Berapa kali pemeriksaan kehamilan      1
16                                  Tempat persalinan     20
17  Anak pernah mengalami ISPA (Infeksi Saluran Pe...     13
18                       Anak pernah mengalami diare?      1
19  Berapa kali frekuensi anak diare dalam setahun...      7
20          Apakah anak batuk dalam 3 bulan terakhir?      6
21                                              Label      1

In [ ]:
# feature selection menggunakan extra tress classifier
from sklearn.ensemble import ExtraTreesClassifier
import matplotlib.pyplot as plt

x = response_data_clear.iloc[:,0:22]
y = response_data_clear.iloc[:,-1]

model = ExtraTreesClassifier()
model.fit(x,y)

print(model.feature_importances_)

feat_importances = pd.Series(model.feature_importances_, index = x.columns)
feat_importances.nlargest(10).plot(kind='barh')
plt.show()

In [ ]:
# feature selection menggunakan information gain
from sklearn.feature_selection import mutual_info_classif
from sklearn.feature_selection import SelectPercentile

x = response_data_clear.iloc[:,0:22]
y = response_data_clear.iloc[:,-1]

MI = mutual_info_classif(x, y)
len(MI)

MI = pd.Series(MI)
MI.index = x.columns
MI.sort_values (ascending = False, inplace = True)
MI.plot.bar(figsize = (10,5))

sel = SelectPercentile(mutual_info_classif, percentile=10)


In [ ]:
#split data training dan test
from sklearn.model_selection import train_test_split

x = response_data_clear.drop(["Label"], axis=1)
feature_list = list(x.columns)
x.head()

y = response_data_clear["Label"]
y.head()

x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.4)
print(x_train.shape)
print(x_test.shape)

(76, 21)
(51, 21)


In [ ]:
#Scalling Data
from sklearn.preprocessing import StandardScaler

feature_scaler = StandardScaler()
x_train = feature_scaler.fit_transform(x_train)
x_test = feature_scaler.fit_transform(x_test)

In [ ]:
#Import random forest classifier
#from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
#Create a Gaussian Classifier
#clf=RandomForestClassifier(max_depth=2, random_state=0)
clf=KNeighborsClassifier(n_neighbors=2)

#Train the model using the training sets y_pred=clf.predict(X_test)
classifier = clf.fit(x_train,y_train)
y_pred = classifier.predict(x_test) 

In [ ]:
#Import scikit-learn metrics module for accuracy calculation
from sklearn import metrics
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

#Model Accuracy, how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

Accuracy: 0.9607843137254902


In [ ]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
print(confusion_matrix(y_test, y_pred))
print(y_test.shape)
print(y_pred.shape)

print	('Accuracy	  :',	round(accuracy_score(y_test, y_pred)*100,2),"%")
print ('Precision	  :', round(precision_score(y_test, y_pred, average='weighted', zero_division=0)*100,2),"%")
print ('Recall	    :', round(recall_score(y_test, y_pred, average='weighted', zero_division=0)*100,2),"%")
print	('f1-score	  :',	round(f1_score(y_test,	y_pred, average='weighted', zero_division=0)*100,2), "%")

[[49  0]
 [ 2  0]]
(51,)
(51,)
Accuracy	  : 96.08 %
Precision	  : 92.31 %
Recall	    : 96.08 %
f1-score	  : 94.16 %


In [ ]:
# hypertuning paramater menggunakan  GridSearch
from sklearn.model_selection import GridSearchCV 
from sklearn.ensemble import RandomForestClassifier

param_grid = {
  'n_estimators': [200, 500, 700], 
  'max_features': ['auto', 'sqrt', 'log2'],
  'max_depth' : [4,5,6,7,8],
  'criterion' :['gini', 'entropy'],
}

rfc=RandomForestClassifier(max_depth=2, random_state=0)
CV_rfc = GridSearchCV(estimator=rfc, param_grid=param_grid, cv = 5)
CV_rfc.fit(x_train, y_train)
CV_rfc.best_params_

{'criterion': 'gini',
 'max_depth': 4,
 'max_features': 'auto',
 'n_estimators': 200}

In [ ]:
# Grid Search test best parameters
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

CV_rfc.best_params_rfc1=RandomForestClassifier(random_state=0, criterion='gini',	max_depth=4, max_features='auto',	n_estimators=	200)
CV_rfc.best_params_rfc1.fit(x_train, y_train) 
pred=CV_rfc.predict(x_test) 
print (pred)

print (confusion_matrix(y_test, pred))
print ('Accuracy	:'	,	round(accuracy_score(y_test, pred)*100,2),"%")
print ('Precision	:', round(precision_score(y_test, pred, average='weighted', zero_division=0)*100,2),"%")
print ('Recall	:', round(recall_score(y_test, pred, average='weighted', zero_division=0)*100,2), "%")
print	('f1-score	:',	round(f1_score(y_test,	pred, average='weighted', zero_division=0)*100,2), "%")

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[[49  0]
 [ 2  0]]
Accuracy	: 96.08 %
Precision	: 92.31 %
Recall	: 96.08 %
f1-score	: 94.16 %


In [ ]:
#split data menggunakan k-fold
from sklearn.model_selection import KFold
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
from sklearn.neighbors import KNeighborsClassifier

kf=KFold(n_splits=10, shuffle = False)
print(kf)  #buat tau Kfold dan parameter defaultnya
i=1        #ini gapenting, cuma buat nandain fold nya.

x = response_data_clear.drop(["Label"], axis=1)
y = response_data_clear["Label"]

feature_scaler = StandardScaler()
x = feature_scaler.fit_transform(x)

def cross_val(estimator):     
  acc = []     
  pcs = []     
  rec = []
  f1s = []
  
  for train_index, test_index in kf.split(x):         
      x_train, x_test = x[train_index], x[test_index]         
      y_train, y_test = y[train_index], y[test_index] 

      model = estimator.fit(x_train, y_train)         
      y_pred = model.predict(x_test)                  
      acc.append(accuracy_score(y_test, y_pred))         
      pcs.append(precision_score(y_test, y_pred, average='macro', zero_division=0))                       
      rec.append(recall_score(y_test, y_pred, average='macro', zero_division=0))
      f1s.append(f1_score(y_test, y_pred, average='macro', zero_division=0))  
      
      print(metrics.classification_report(y_test, y_pred, zero_division=0))
      print(f'confusion matrix:\n {metrics.confusion_matrix(y_test, y_pred)}')        
      print('================================================\n')  

  print(f'average akurasi: {np.mean(acc)}')
  print(f'average precision: {np.mean(pcs)}')
  print(f'average recall: {np.mean(rec)}')
  print(f'average f1-score: {np.mean(f1s)}')  

from sklearn.ensemble import RandomForestClassifier

clf=KNeighborsClassifier(metric='minkowski', n_neighbors=2, weights='uniform')
cross_val(clf)

In [ ]:
# hypertuning paramater menggunakan  GridSearch
from sklearn.model_selection import GridSearchCV 
from sklearn.neighbors import KNeighborsClassifier

param_grid = {
  'n_neighbors': [3, 5, 11, 19], 
  'metric': ['minkowski', 'euclidean', 'manhattan'],
  'weights' : ['uniform', 'distance'],
}

knn = KNeighborsClassifier(n_neighbors=2)
CV_knn = GridSearchCV(estimator=knn, param_grid=param_grid, cv = 5)
CV_knn.fit(x_train, y_train)
CV_knn.best_params_ 

{'metric': 'minkowski', 'n_neighbors': 5, 'weights': 'uniform'}

In [ ]:
# Grid Search test best parameters
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

CV_knn.best_params_knn1= KNeighborsClassifier(metric='minkowski', n_neighbors=5, weights= 'uniform')
CV_knn.best_params_knn1.fit(x_train, y_train) 
pred=CV_knn.predict(x_test) 
print (pred)

print (confusion_matrix(y_test, pred))
print ('Accuracy	:'	,	round(accuracy_score(y_test, pred)*100,2),"%")
print ('Precision	:', round(precision_score(y_test, pred, average='weighted', zero_division=0)*100,2),"%")
print ('Recall	:', round(recall_score(y_test, pred, average='weighted', zero_division=0)*100,2), "%")
print	('f1-score	:',	round(f1_score(y_test,	pred, average='weighted', zero_division=0)*100,2), "%")

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[[49  0]
 [ 2  0]]
Accuracy	: 96.08 %
Precision	: 92.31 %
Recall	: 96.08 %
f1-score	: 94.16 %


In [ ]:
# Grid Search test best parameters
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
from sklearn.neighbors import KNeighborsClassifier

CV_knn.best_params_knn1=KNeighborsClassifier(metric='minkowski', n_neighbors=2, weights='uniform')
CV_knn.best_params_knn1.fit(x_train, y_train) 
pred=CV_knn.predict(x_test) 
print (pred)

print (confusion_matrix(y_test, pred))
print ('Accuracy	:'	,	round(accuracy_score(y_test, pred)*100,2),"%")
print ('Precision	:', round(precision_score(y_test, pred, average='weighted')*100,2),"%")
print ('Recall	:', round(recall_score(y_test, pred, average='weighted')*100,2), "%")
print	('f1-score	:',	round(f1_score(y_test,	pred, average='weighted')*100,2), "%")

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[[25  0]
 [ 1  0]]
Accuracy	: 96.15 %
Precision	: 92.46 %
Recall	: 96.15 %
f1-score	: 94.27 %


/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [ ]:
#print(x_test.shape)
#testing precision
#TP = 47
#FN = 0
#FP = 4
#TN = 0

#precision =TP/(TP+FP)
#precision

In [ ]:
#load library
import seaborn as sns
import matplotlib.pyplot as plt

CM = confusion_matrix(y_train, pred)
plt.figure(figsize=(9,5))
axes = sns.heatmap(CM, annot= True)
plt.xlabel('Actual')
plt.ylabel('Predicted Model')
plt.title('Confusion Matrix')

class_Label = ['Data Tidak Stunting','Data Stunting']
class_prediction = ['Data Tidak Stunting','Data Stunting']

tick_marks = np.arange(len(class_Label)) + 0.5

axes.set_xticks(tick_marks + 0.3)
axes.set_xticklabels(class_Label, rotation=0)

axes.set_yticks(tick_marks + 0.3)
axes.set_yticklabels(class_prediction, rotation=0)

plt.show()

In [ ]:
#plot tree
# Import tools needed for visualization
from sklearn.tree import export_graphviz
import pydot

# Pull out one tree from the forest
tree = classifier.estimators_[10]

# Import tools needed for visualization
from sklearn.tree import export_graphviz
import pydot

tree = classifier.estimators_[10]

# Export the image to a dot file
export_graphviz(tree, out_file = 'tree.dot', feature_names = feature_list, rounded = True, precision = 1)

# Use dot file to create a graph
(graph, ) = pydot.graph_from_dot_file('tree.dot')
# Write graph to a png file
graph.write_png('tree.png')